### ISSUE TITLE
Installing a plugin should be idempotence

### ISSUE THREAD

**Issue by robiness** [phntmxyz/sidekick#129]
When testing a new plugin locally i want to call `plugins install` multiple times to just update my plugin in the sidekick project.

`plugins install` always does add the command to the command list. Even though it's already present.
 This leads to `Invalid argument(s): Duplicate command "docker".` when running the command.

<img width="309" alt="image" src="https://user-images.githubusercontent.com/34774539/205502112-bb444003-50d9-4a6a-9f20-ccc4779c52ab.png">

Can i create a PR for this?

**Comment by passsy** [comment]
Yes, go ahead and create a PR. [registerPlugin()](https://github.com/phntmxyz/sidekick/blob/cec46dbfe741ec3a48705acc2ac3837c54a0bf84/sidekick_plugin_installer/lib/src/register_plugin.dart#LL9C22-L9C22) is missing the duplication check
