### ISSUE TITLE
Add Link to discover available Plugins to readme

### ISSUE THREAD

**Issue by jxstxn1** [phntmxyz/sidekick#134]
I think it would be nice if there is a Link where I can see all existing Sidekick Plugins in the readme.

I think this would be enough:
[Check out all available Sidekick Plugins](https://pub.dev/packages?q=dependency:sidekick_plugin_installer)

**Comment by passsy** [comment]
<img width="740" alt="Screen-Shot-2022-12-08-12-04-26 33" src="https://user-images.githubusercontent.com/1096485/206431050-b8fab428-8a4c-44fb-893a-bbc2086eb92b.png">

It's there, have expected it anywhere else?

**Comment by jxstxn1** [comment]
No
I just completely have overseen it, expected it to be "more visible"

**Comment by passsy** [comment]
Fixed in 26e5080561e56fe161e73fdca16a2b00c82412e9
