### ISSUE TITLE
VersionChecker doesn't check without command

### ISSUE THREAD

**Issue by passsy** [phntmxyz/sidekick#143]
VersionChecker is not executed when just calling the cli, it always requires an argument

```
$ export SIDEKICK_ENABLE_UPDATE_CHECK=true 
$ noa
```
(no check)

```
$ export SIDEKICK_ENABLE_UPDATE_CHECK=true
$ noa vault
```
(does the check)

The reason for this is, that we do an early return for zero args

```
  if (args.isEmpty) {
    print(runner.usage);
    return;
  }
```

**Comment by Giuspepe** [comment]
Will be fixed by #157
