### ISSUE TITLE
Updating transitive dependency of `file`

### ISSUE THREAD

**Issue by robiness** [phntmxyz/sidekick#50]
@passsy @jxstxn1 On current flutter master there was a breaking change regarding file handling which is used in `file` and fixed with `file 6.1.3`.

`file` is a transitive dependency here because of `dcli`, which we ideally should update but it seems that we do not want that:
https://github.com/phntmxyz/sidekick/blob/69873f585a8160ebf701baba824091e78cdfc7ef/sidekick_core/pubspec.yaml#L12

What do you think about this? Should we update `dcli` anyway or `dependecy_override` file?

**Comment by passsy** [comment]
We should update dcli at this point. But it requires us to increase the minSdk

**Comment by robiness** [comment]
It actually did not cause the problem. Do you want me to upgrade it anyway? Current dcli depends on `2.18` which is also stable since May, so at a first glance it looks fine.

**Comment by passsy** [comment]
Thanks for letting me know. I'm closing this.

The upgrade is still planned, but I don't know how far. We want to make sure to always support the latest 3 dart versions. Therefore would bump from `2.14` -> `2.16`
