### ISSUE TITLE
Breaking cli app when switching flutter versions

### ISSUE THREAD

**Issue by robiness** [phntmxyz/sidekick#51]
The last days i experience a weird behavior when switching flutter versions. 
Sidekick will not be installed/reinstalled because of missing dart sdk. Even though it's there.

```
➜  adb-frontend git:(irn-1575-mfa-api) adb flutter --version
Installing 'adb' command line application...
- Getting dependencies
.../adb_sidekick/tool/install.sh: line 30: ../.flutter/bin/cache/dart-sdk/bin/dart: No such file or directory
```

Workaround:
Going into `.flutter/bin` and calling `./flutter --version` will download the correct version and it works afterwards.

**Comment by passsy** [comment]
This is not an issue anymore with the embedded dart SDK.

Please update your cli `<cli> sidekick update`, available since `sidekick_core: 0.13.0`
